version: "3.8"
services:
  api:
    build: .
    image: staking-validator-api:latest
    container_name: staking-validator-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/root/config.json:ro